### ISSUE TITLE
모든 프로젝트가 표시되지 않는 듯합니다

### ISSUE THREAD

**Issue by wafe** [mantech-oss/jira-search-helper#14]
저희가 프로젝트가 많아서 그런지 프로젝트 선택 목록에 나오지 않는 프로젝트가 많습니다. ㅠ.ㅠ 
표시되지 않는 기준이 있어서 그런걸까요...

**Comment by nurinamu** [comment]
저도 동일합니다.
저희는 프로젝트가 4개 뿐인데도 하나랑 TEST 란게 뜨네요.

그리고 log console에 No jira/globalnavigator/breadcrumbs/bridge 에러가..

**Comment by oscarplex** [comment]
저희 쪽 설치형 jira 에서는 store.ts 의 getProjectList() 에서 사용하는 rest/api/2/project/search 로는 404 가 떠서

[rest/api/2/project](https://docs.atlassian.com/software/jira/docs/api/REST/8.2.0/?_ga=2.111455874.746998918.1558343025-232874918.1557136424#api/2/project-getAllProjects)

이 api 로 요청, 응답을 변경하니 되긴 합니다.

**Comment by taeuk-gang** [comment]
@oscarplex 클라우드형에서는 반대로 [rest/api/2/project](https://docs.atlassian.com/software/jira/docs/api/REST/8.2.0/?_ga=2.111455874.746998918.1558343025-232874918.1557136424#api/2/project-getAllProjects) 가 404 떠서, 버전별로 틀려질 수가 있을 것 같아요.

**Comment by taeuk-gang** [comment]
@wafe 현재는 `/rest/api/2/project` JIRA API 통하여 HTTP GET 요청하고 있는데, JIRA 버전 및 설치형(on-premise)에 따라 다른지 확인 필요할 것 같아요.

AS-IS(현재)
- `/rest/api/2/project`만 고려하여 프로젝트 목록 요청

TO-BE(개선 방향)
- JIRA 버전 및 설치형(on-premise)에 따라 다른지 확인 필요

**Comment by oscarplex** [comment]
> @oscarplex 클라우드형에서는 반대로 [rest/api/2/project](https://docs.atlassian.com/software/jira/docs/api/REST/8.2.0/?_ga=2.111455874.746998918.1558343025-232874918.1557136424#api/2/project-getAllProjects) 가 404 떠서, JIRA 환경별로 다를 수가 있을 것 같아요.

그래서 이걸 pr 로 요청하기가 애매하더라고요... 일단은 감사히 쓰겠습니다. ㅎㅎ

**Comment by wafe** [comment]
엇.. 저희는 클라우드 형인데, 목록이 아주 많이 나오기는 하지만 전체는 아닌 상황이에요.  페이징이 걸려있을지도 모르겠네요.

**Comment by taeuk-gang** [comment]
> 엇.. 저희는 클라우드 형인데, 목록이 아주 많이 나오기는 하지만 전체는 아닌 상황이에요. 페이징이 걸려있을지도 모르겠네요.

```
/rest/api/2/project/search
```
<img width="425" alt="image" src="https://user-images.githubusercontent.com/26294469/191010142-df04eccc-5e14-478d-97dd-06a75aeea782.png">


확인해보니 말씀하신 것처럼 페이징이 50개까지가 기본값이네요. [JIRA Rest  Docs](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-projects/#api-rest-api-2-project-search-get)를 살펴보았는데 `maxResults=100`으로 파라미터를 주고 있음에도, 50 초과하여 받아오지 못하는걸 보아 API Spec 상 지원  안되는 것 같아요.

### 현재 `maxResults` 파라미터

https://github.com/mantech-oss/jira-search-helper/blob/a37b4852d15777907c838a9ad7333c4986d01b0c/src/content/apis/project-list.ts#L97


### 현재 Response

#### Request

<img width="860" alt="image" src="https://user-images.githubusercontent.com/26294469/191013516-31b93f78-ba0e-406e-a4f3-40b965a1468d.png">

#### Response

<img width="857" alt="스크린샷 2022-09-19 오후 9 04 13" src="https://user-images.githubusercontent.com/26294469/191013414-fd373f20-f6c9-4521-a76c-2d4c825145d7.png">

**Comment by taeuk-gang** [comment]
개선을 위해서 결론은 `isLast` === `true`가 될때까지 API 요청이 필요할 것 같아요.

**Comment by wafe** [comment]
설치된 크롬 확장 기능을 개발자 모드로 수정(정렬을 프로젝트 key로)해서 제가 원하는 프로젝트 검색을 해보니 검색이 잘 됩니다! :) 

minify 된 코드라서 루프돌면서 isLast true 일 때까지 수정하는 것은 못해봤습니다...

다만, 한글 두글자만 검색하려고 하면 결과가 안나오는 문제가 있는데 이게 JIRA 문제일지 아닌지 모르겠습니다.

**Comment by taeuk-gang** [comment]
## TODO

- [ ] 설치형 JIRA를 위한 옵션 추가 (요청 API Path 변경)
- [ ] 프로젝트 전체 목록을 가져오기위한 로직 추가

**Comment by taeuk-gang** [comment]
주말에 잠깐 살펴봤는데, 정확하게는 Get All Ptojects API가 Deprecated되어, 클라우드형에서 사용은 비권장되고(작동은 함)

참고 이미지.
![image](https://user-images.githubusercontent.com/26294469/192093496-d962bbe7-668e-404e-96c2-c982c61ac88b.png)

JIRA On-premise 환경에서는 사용 권고되는 `/rest/api/2/project/search` 가 반대로 없어 문제가 되는 이슈로 판단됩니다.

그래서 두가지 옵션 둘다 제공을 위해 별도 옵션을 추가하였습니다.

![image](https://user-images.githubusercontent.com/26294469/192093556-b147d5b9-14f5-44fd-bbf6-01e15e6f3da4.png)

+ 추가사항. `/rest/api/2/project/search` 에서는 페이징 처리가 되어 50개 최대로 들고올 수 없어 별도로 프로젝트를 전부 가져오는 로직을 추가하였습니다. ([관련 커밋](https://github.com/mantech-oss/jira-search-helper/commit/6e95702bcbcb81f61f335229507717ce2de3ec3f))

**Comment by taeuk-gang** [comment]
위 내용은 v1.0.1 패치내역에 포함되어 해결될 예정으로 v1.0.1 릴리즈되면 이슈 정상해결로 클로즈하겠습니다.

**Comment by taeuk-gang** [comment]
v1.1.0 릴리즈로 해결되어 이슈를 닫습니다.
